version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./application:/www"
      - "/www/node_modules"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27018:27017"